name: Envoyer une notification discord lors de modifications sur le repo.
on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - edited
      - review_requested
      - review_request_removed
  issues:
    types:
      - opened
      - closed
      - reopened
      - edited
  fork:
  release:
    types:
      - published
      - edited
      - prereleased
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Push Notification
        if: ${{ github.event_name == 'push' }}
        uses: appleboy/discord-action@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            📢 **Commit détecté !**
            - **Dépôt** : ${{ github.repository }}
            - **Acteur** : ${{ github.actor }}
            - **Message** : ${{ github.event.head_commit.message }}
            - **Lien du commit** : ${{ github.event.head_commit.url }}

      - name: Pull Request Opened Notification
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
        uses: appleboy/discord-action@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            🚀 **Nouvelle Pull Request !**
            - **Dépôt** : ${{ github.repository }}
            - **Auteur** : ${{ github.actor }}
            - **Titre** : ${{ github.event.pull_request.title }}
            - **Description** : ${{ github.event.pull_request.body }}
            - **Lien** : ${{ github.event.pull_request.html_url }}

      - name: Pull Request Closed Notification
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
        uses: appleboy/discord-action@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            ✅ **Pull Request fermée !**
            - **Dépôt** : ${{ github.repository }}
            - **Auteur** : ${{ github.actor }}
            - **Titre** : ${{ github.event.pull_request.title }}
            - **Lien** : ${{ github.event.pull_request.html_url }}

      - name: Issue Opened Notification
        if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
        uses: appleboy/discord-action@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            📝 **Nouvelle Issue !**
            - **Dépôt** : ${{ github.repository }}
            - **Auteur** : ${{ github.actor }}
            - **Titre** : ${{ github.event.issue.title }}
            - **Description** : ${{ github.event.issue.body }}
            - **Lien** : ${{ github.event.issue.html_url }}

      - name: Fork Notification
        if: ${{ github.event_name == 'fork' }}
        uses: appleboy/discord-action@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            🍴 **Nouveau fork !**
            - **Dépôt original** : ${{ github.repository }}
            - **Fork réalisé par** : ${{ github.actor }}
            - **Lien du fork** : ${{ github.event.forkee.html_url }}

      - name: Release Published Notification
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: appleboy/discord-action@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            🎉 **Nouvelle Release !**
            - **Dépôt** : ${{ github.repository }}
            - **Auteur** : ${{ github.actor }}
            - **Nom** : ${{ github.event.release.name }}
            - **Description** : ${{ github.event.release.body }}
            - **Lien** : ${{ github.event.release.html_url }}
